//! Floorp / Firefox renderer.
//!
//! Floorp (like Firefox) reads a `user.js` file from each profile
//! directory at startup. Any `user_pref("key", value);` line in
//! user.js acts as a per-profile override that Floorp respects on
//! every launch and can't be changed away through the UI.
//!
//! kara-beautify writes a small user.js into the active profile
//! with just the handful of prefs that drive the content-area
//! dark/light mode. Everything else in the profile (bookmarks,
//! history, extensions, sessionstore, etc.) is untouched.
//!
//! The prefs we set:
//!
//!   ui.systemUsesDarkTheme
//!     Integer. 0 = system is light, 1 = system is dark. Overrides
//!     Floorp's auto-detect from GTK, which can drift on non-GNOME
//!     desktops.
//!
//!   layout.css.prefers-color-scheme-content-override
//!     Integer. 0 = force light, 1 = force dark, 2 = auto (match OS).
//!     Controls what web content sees via `prefers-color-scheme`
//!     media queries, independent of chrome theme.
//!
//!   widget.content.allow-gtk-dark-theme
//!     Bool. Lets GTK widgets inside web content (select menus,
//!     scrollbars) render dark. Harmless when set on light themes.
//!
//!   widget.use-xdg-desktop-portal.file-picker
//!     Integer. 0 = never, 1 = auto, 2 = always. Forces Floorp to
//!     route Attach/Save-As through xdg-desktop-portal.FileChooser
//!     instead of its built-in GTK dialog — so kara's termfilechooser
//!     routing (see /usr/share/xdg-desktop-portal/kara-portals.conf)
//!     can send the dialog to yazi. Without this the portal stack
//!     is unused for file dialogs and users see the GTK file chooser
//!     no matter how the portal backend is configured. `2` (always)
//!     is the right value for kara — the portal is a hard dep.
//!
//! Live reload note: Floorp parses user.js once at startup; the
//! user needs to restart Floorp for changes to stick. In practice,
//! for a theme swap with an already-running Floorp, the gsettings
//! color-scheme call beautify makes via sync_desktop_appearance
//! usually flips content-area dark mode within a second or two
//! without a restart (Firefox watches the D-Bus settings portal).
//! user.js is the belt-and-suspenders backup for the cases where
//! that doesn't fire.

use crate::{ResolvedTheme, UiMode};

pub fn render_floorp_user_js(theme: &ResolvedTheme) -> String {
    let is_dark = matches!(theme.mode, UiMode::Dark | UiMode::Auto);
    let system_theme = if is_dark { 1 } else { 0 };
    let content_override = if is_dark { 1 } else { 0 };
    let allow_gtk_dark = if is_dark { "true" } else { "false" };

    format!(
        "// generated by kara-beautify for theme: {name}
// DO NOT EDIT — this file is overwritten on every `kara-beautify apply`.
// Set consumers.floorp = false in ~/.config/kara/kara-beautify.toml
// if you'd rather manage these prefs yourself.
//
// Floorp reads user.js once at startup. Open a fresh window (or
// restart the browser) for content-area dark mode to take full
// effect if gsettings hasn't already propagated via the D-Bus
// settings portal.

user_pref(\"ui.systemUsesDarkTheme\", {system_theme});
user_pref(\"layout.css.prefers-color-scheme-content-override\", {content_override});
user_pref(\"widget.content.allow-gtk-dark-theme\", {allow_gtk_dark});

// Route file dialogs (Attach, Save As, Download show-in-folder) through
// xdg-desktop-portal so kara FileChooser routing lands in yazi via
// termfilechooser. Value 2 = always use the portal.
user_pref(\"widget.use-xdg-desktop-portal.file-picker\", 2);
user_pref(\"widget.use-xdg-desktop-portal.mime-handler\", 2);
",
        name = theme.name,
    )
}
