use crate::{ResolvedTheme, UiMode};

/// Render a foot theme include file.
///
/// foot's color sections are mode-scoped: `[colors-dark]` applies
/// when foot runs in dark mode (detected from GTK/portal or set via
/// `[main] theme=dark`), `[colors-light]` applies in light mode.
/// `[colors]` is a fallback that applies regardless of mode but is
/// overridden by either mode-specific section.
///
/// We emit the palette into the section matching the resolved
/// theme's mode so foot's live dark/light detection still works —
/// if the user later sets `theme=auto` and flips the system
/// color-scheme, foot applies the right section automatically.
///
/// Users pull this file in from their main foot.ini with
/// `include=~/.local/state/kara/generated/foot-theme.ini`. Live
/// reload after `kara-beautify apply`: `pkill -USR1 -x foot`.
///
/// The ANSI palette uses `theme.ansi[0..16]` — the same 16-color
/// lookup kitty/tmux consume — so color families stay aligned
/// across terminals.
pub fn render_foot_theme(theme: &ResolvedTheme) -> String {
    let c = &theme.semantic;
    // foot wants colors as 6-digit hex with NO leading '#'.
    let strip = |hex: String| -> String { hex.trim_start_matches('#').to_string() };

    // Pick the section that matches the theme's resolved mode so
    // foot's mode-scoped color dispatch still works.
    let section = match theme.mode {
        UiMode::Light => "colors-light",
        UiMode::Dark | UiMode::Auto => "colors-dark",
    };

    format!(
        "# generated by kara-beautify for theme: {name}
# DO NOT EDIT — edit your theme in themes/<theme>/theme.toml instead.
#
# Include this from your main foot.ini with:
#   include=~/.local/state/kara/generated/foot-theme.ini
# SIGUSR1 to foot to live-reload after a kara-beautify apply.

[{section}]
alpha={alpha:.2}
foreground={foreground}
background={background}
selection-foreground={sel_fg}
selection-background={sel_bg}

urls={urls}

regular0={r0}
regular1={r1}
regular2={r2}
regular3={r3}
regular4={r4}
regular5={r5}
regular6={r6}
regular7={r7}

bright0={b0}
bright1={b1}
bright2={b2}
bright3={b3}
bright4={b4}
bright5={b5}
bright6={b6}
bright7={b7}
",
        name = theme.name,
        alpha = theme.style.opacity,
        foreground = strip(c.fg0.to_hex()),
        background = strip(c.bg0.to_hex()),
        sel_fg = strip(c.selection_fg.to_hex()),
        sel_bg = strip(c.selection_bg.to_hex()),
        urls = strip(c.accent.to_hex()),
        r0 = strip(theme.ansi[0].to_hex()),
        r1 = strip(theme.ansi[1].to_hex()),
        r2 = strip(theme.ansi[2].to_hex()),
        r3 = strip(theme.ansi[3].to_hex()),
        r4 = strip(theme.ansi[4].to_hex()),
        r5 = strip(theme.ansi[5].to_hex()),
        r6 = strip(theme.ansi[6].to_hex()),
        r7 = strip(theme.ansi[7].to_hex()),
        b0 = strip(theme.ansi[8].to_hex()),
        b1 = strip(theme.ansi[9].to_hex()),
        b2 = strip(theme.ansi[10].to_hex()),
        b3 = strip(theme.ansi[11].to_hex()),
        b4 = strip(theme.ansi[12].to_hex()),
        b5 = strip(theme.ansi[13].to_hex()),
        b6 = strip(theme.ansi[14].to_hex()),
        b7 = strip(theme.ansi[15].to_hex()),
    )
}
