use crate::ResolvedTheme;

/// Render a foot theme include file.
///
/// foot.ini has its own INI syntax with a `[colors]` section. Users
/// pull this generated file in via `include=~/.config/foot/foot-theme.ini`
/// in their main `foot.ini`. foot reloads colors live when the file
/// changes (via `pkill -USR1 foot` or the reload plan wired in
/// kara-beautify/src/reload.rs).
///
/// The ANSI palette uses `theme.ansi[0..16]` — the same 16-color lookup
/// kitty/tmux consume — so color families stay aligned across terminals.
pub fn render_foot_theme(theme: &ResolvedTheme) -> String {
    let c = &theme.semantic;
    // foot wants colors as 6-digit hex with NO leading '#'.
    let strip = |hex: String| -> String { hex.trim_start_matches('#').to_string() };

    format!(
        "# generated by kara-beautify for theme: {name}
# DO NOT EDIT — edit your theme in themes/<theme>/theme.toml instead.
#
# Include this from your main foot.ini with:
#   include=~/.local/state/kara/generated/foot-theme.ini
# The include is loaded AFTER your inline [colors] block so it wins.
# SIGUSR1 to foot to live-reload after a kara-beautify apply.

[main]
font={font_family}:size={font_size}

[colors]
alpha={alpha:.2}
foreground={foreground}
background={background}
selection-foreground={sel_fg}
selection-background={sel_bg}

urls={urls}

regular0={r0}
regular1={r1}
regular2={r2}
regular3={r3}
regular4={r4}
regular5={r5}
regular6={r6}
regular7={r7}

bright0={b0}
bright1={b1}
bright2={b2}
bright3={b3}
bright4={b4}
bright5={b5}
bright6={b6}
bright7={b7}
",
        name = theme.name,
        font_family = theme.fonts.mono_family,
        font_size = theme.fonts.mono_size,
        alpha = theme.style.opacity,
        foreground = strip(c.fg0.to_hex()),
        background = strip(c.bg0.to_hex()),
        sel_fg = strip(c.selection_fg.to_hex()),
        sel_bg = strip(c.selection_bg.to_hex()),
        urls = strip(c.accent.to_hex()),
        r0 = strip(theme.ansi[0].to_hex()),
        r1 = strip(theme.ansi[1].to_hex()),
        r2 = strip(theme.ansi[2].to_hex()),
        r3 = strip(theme.ansi[3].to_hex()),
        r4 = strip(theme.ansi[4].to_hex()),
        r5 = strip(theme.ansi[5].to_hex()),
        r6 = strip(theme.ansi[6].to_hex()),
        r7 = strip(theme.ansi[7].to_hex()),
        b0 = strip(theme.ansi[8].to_hex()),
        b1 = strip(theme.ansi[9].to_hex()),
        b2 = strip(theme.ansi[10].to_hex()),
        b3 = strip(theme.ansi[11].to_hex()),
        b4 = strip(theme.ansi[12].to_hex()),
        b5 = strip(theme.ansi[13].to_hex()),
        b6 = strip(theme.ansi[14].to_hex()),
        b7 = strip(theme.ansi[15].to_hex()),
    )
}
