use crate::ResolvedTheme;

pub fn render_fzf_theme(theme: &ResolvedTheme) -> String {
    let c = &theme.semantic;
    format!(
        "# generated by kara-beautify
export KARA_FZF_COLOR_OPTS=\"--color=bg:-1,bg+:-1,fg:{},fg+:{},hl:{},hl+:{},info:{},prompt:{},pointer:{},marker:{},spinner:{},header:{}\"
",
        c.fg0.to_hex(),
        c.selection_fg.to_hex(),
        c.accent.to_hex(),
        c.accent.to_hex(),
        c.fg_muted.to_hex(),
        c.accent.to_hex(),
        c.accent.to_hex(),
        c.accent.to_hex(),
        c.accent.to_hex(),
        c.accent.to_hex(),
    )
}
