use crate::ResolvedTheme;

fn hex_to_vwm(hex: &str) -> String {
    format!("0x{}", hex.trim_start_matches('#'))
}

pub fn render_kara_gate_theme(theme: &ResolvedTheme) -> String {
    let c = &theme.semantic;
    let bar = &theme.vwm_bar;

    let (
        module_gap,
        module_padding_x,
        module_padding_y,
        module_radius,
        module_bg,
        module_fg,
        module_border,
    ) = match theme.name.as_str() {
        "gruvbox" => (8, 10, 1, 0, c.bg1, c.fg0, c.border_subtle),
        "vague" => (9, 10, 2, 10, c.bg1.lighten(0.02), c.fg0, c.border_subtle),
        "cloud" => (14, 14, 5, 18, c.bg1, c.fg0, c.border_strong),
        _ => (12, 12, 4, bar.radius, c.bg1, c.fg0, c.border_subtle),
    };

    format!(
        "# generated by kara-beautify

rules {{
    float class \"kara\"
}}

general {{
    border_px 2
    gap_px 12
}}

theme {{
    bg {}
    surface {}
    text {}
    text_muted {}
    accent {}
    accent_soft {}
    border {}
}}

bar {{
    enabled true
    background {}
    modules {}
    icons {}
    colors {}
    minimal {}

    position top
    style {}
    height {}
    radius {}

    margin_x {}
    margin_y {}

    content_margin_x 12
    content_margin_y 2

    gap {}
    padding_x {}
    padding_y {}

    module_gap {}
    module_padding_x {}
    module_padding_y {}
    module_radius {}
    module_bg {}
    module_fg {}
    module_border {}
    module_border_width 1

    volume_bar_enabled true
    volume_bar_width 38
    volume_bar_height 8
    volume_bar_radius 10
}}
",
        hex_to_vwm(&c.bg0.to_hex()),
        hex_to_vwm(&c.bg1.to_hex()),
        hex_to_vwm(&c.fg0.to_hex()),
        hex_to_vwm(&c.fg_muted.to_hex()),
        hex_to_vwm(&c.accent.to_hex()),
        hex_to_vwm(&c.accent_soft.to_hex()),
        hex_to_vwm(&c.border_subtle.to_hex()),
        if bar.background { "true" } else { "false" },
        bar.modules,
        if bar.icons { "true" } else { "false" },
        if bar.colors { "true" } else { "false" },
        if bar.minimal { "true" } else { "false" },
        bar.style,
        bar.height,
        bar.radius,
        bar.margin_x,
        bar.margin_y,
        module_gap,
        module_padding_x,
        bar.padding_y,
        module_gap,
        module_padding_x,
        module_padding_y,
        module_radius,
        hex_to_vwm(&module_bg.to_hex()),
        hex_to_vwm(&module_fg.to_hex()),
        hex_to_vwm(&module_border.to_hex()),
    )
}
