use crate::ResolvedTheme;

/// Optional context passed by kara-beautify into the kara-gate
/// renderer. Carries the paths of any PNG tiles rasterized from the
/// theme's SVG slots — window_border.svg_tile today, bar tiles when
/// kara-sight picks them up. kara-gate reads these paths via its
/// existing `general { border_tile = "..." }` config key and swaps
/// the SolidColor pattern for a repeating PNG pattern in the same
/// tiny-skia render path it uses today.
///
/// When `None` is passed, the renderer behaves exactly as before.
#[derive(Debug, Default, Clone)]
pub struct KaraGateRenderContext<'a> {
    /// Absolute filesystem path of the rasterized window-border tile
    /// PNG, if the theme set `window_border.svg_tile` and the tile
    /// rasterized successfully. `None` → fall back to solid-color
    /// border fill.
    pub window_border_tile_path: Option<&'a std::path::Path>,
}

fn hex_to_kara(hex: &str) -> String {
    format!("0x{}", hex.trim_start_matches('#'))
}

/// Render a kara-gate theme include file. kara-beautify writes this to
/// `~/.local/state/kara/generated/kara-gate-theme.conf` and the user's
/// `kara-gate.conf` pulls it in with an `include` directive near the
/// bottom (so it overrides any inline theme block above).
///
/// The palette block is always emitted. When the active theme sets a
/// `[window_border]` section, an additional `general { }` block emits
/// the width / radius overrides and the focused / unfocused colors
/// replace the semantic defaults in the `theme { }` block. Themes
/// without `[window_border]` stay palette-only, preserving the old
/// "user owns layout, beautify owns color" behavior.
pub fn render_kara_gate_theme(theme: &ResolvedTheme) -> String {
    render_kara_gate_theme_with(theme, &KaraGateRenderContext::default())
}

pub fn render_kara_gate_theme_with(
    theme: &ResolvedTheme,
    ctx: &KaraGateRenderContext<'_>,
) -> String {
    let c = &theme.semantic;

    // `theme.name` is either "<theme>" (single-palette theme) or
    // "<theme>:<variant>" (multi-variant). Split the variant off so
    // the comment shows "theme: default (variant: nord)" with a real
    // source-file path instead of the resolved identifier.
    let (theme_dir, display_header) = match theme.name.split_once(':') {
        Some((t, v)) => (t, format!("{t} (variant: {v})")),
        None => (theme.name.as_str(), theme.name.clone()),
    };

    // Resolve border colors — palette refs like "$accent" become hex,
    // literal hex passes through, missing fields fall back to the
    // semantic defaults.
    let focused_color = theme
        .window_border
        .as_ref()
        .and_then(|wb| wb.color_focused.as_deref())
        .map(|s| theme.resolve_palette_ref(s))
        .unwrap_or_else(|| c.accent.to_hex().trim_start_matches('#').to_string());
    let border_color = theme
        .window_border
        .as_ref()
        .and_then(|wb| wb.color_unfocused.as_deref())
        .map(|s| theme.resolve_palette_ref(s))
        .unwrap_or_else(|| c.border_subtle.to_hex().trim_start_matches('#').to_string());

    let mut out = format!(
        "# generated by kara-beautify for theme: {display_header}
# DO NOT EDIT — edit your theme in themes/{theme_dir}/theme.toml instead.
#
# This file is loaded via `include` from your kara-gate.conf. It
# overrides whatever inline theme / general blocks you have above
# the include line.

theme {{
    bg          {bg}
    surface     {surface}
    text        {text}
    text_muted  {text_muted}
    accent      {accent}
    accent_soft {accent_soft}
    border      {border}
}}
",
        bg = hex_to_kara(&c.bg0.to_hex()),
        surface = hex_to_kara(&c.bg1.to_hex()),
        text = hex_to_kara(&c.fg0.to_hex()),
        text_muted = hex_to_kara(&c.fg_muted.to_hex()),
        accent = hex_to_kara(&focused_color),
        accent_soft = hex_to_kara(&c.accent_soft.to_hex()),
        border = hex_to_kara(&border_color),
    );

    // Width + radius override, only when the theme opts in.
    if let Some(wb) = theme.window_border.as_ref() {
        if wb.width.is_some() || wb.radius.is_some() {
            out.push('\n');
            out.push_str("general {\n");
            if let Some(w) = wb.width {
                out.push_str(&format!("    border_px     {w}\n"));
            }
            if let Some(r) = wb.radius {
                out.push_str(&format!("    border_radius {r}\n"));
            }
            out.push_str("}\n");
        }
        if let Some(tile) = ctx.window_border_tile_path {
            // Rasterized PNG path. kara-config's General struct picks
            // up `border_tile` as an Option<PathBuf> that kara-gate's
            // border rasterizer tiles across the border rect instead
            // of the solid color above.
            out.push('\n');
            out.push_str("general {\n");
            out.push_str(&format!("    border_tile   {}\n", tile.display()));
            out.push_str("}\n");
        } else if wb.svg_tile.is_some() {
            out.push_str("\n# NOTE: [window_border.svg_tile] was set but the rasterizer\n");
            out.push_str("# did not produce a tile path (missing file / parse error).\n");
            out.push_str("# Falling back to the solid-color border above.\n");
        }
    }

    out
}
