use crate::ResolvedTheme;

fn hex_to_kara(hex: &str) -> String {
    format!("0x{}", hex.trim_start_matches('#'))
}

/// Render a kara-gate theme include file. kara-beautify writes this to
/// `~/.local/state/kara/generated/kara-gate-theme.conf` and the user's
/// `kara-gate.conf` pulls it in with an `include` directive near the
/// bottom (so it overrides any inline theme block above).
///
/// This file is **colors-only** by design. Layout (bar geometry, border
/// px, gaps, radii) stays in the user's own config. Beautify owns the
/// palette; the user owns the spatial model. When extended theming
/// lands in a later beautify milestone, we'll grow this renderer to
/// emit optional layout overrides for themes that want distinct module
/// shapes or bar decorations — but palette-only is the right scope for
/// v1 and keeps user customization sticky.
pub fn render_kara_gate_theme(theme: &ResolvedTheme) -> String {
    let c = &theme.semantic;

    // `theme.name` is either "<theme>" (single-palette theme) or
    // "<theme>:<variant>" (multi-variant). Split the variant off so
    // the comment shows "theme: default (variant: nord)" with a real
    // source-file path instead of the resolved identifier.
    let (theme_dir, display_header) = match theme.name.split_once(':') {
        Some((t, v)) => (t, format!("{t} (variant: {v})")),
        None => (theme.name.as_str(), theme.name.clone()),
    };

    format!(
        "# generated by kara-beautify for theme: {display_header}
# DO NOT EDIT — edit your theme in themes/{theme_dir}/theme.toml instead.
#
# This file is loaded via `include` from your kara-gate.conf. It
# overrides whatever inline `theme {{ }}` block you have above the
# include line. Bar layout, border px, and gaps stay in your own
# config — this file is colors-only.

theme {{
    bg          {bg}
    surface     {surface}
    text        {text}
    text_muted  {text_muted}
    accent      {accent}
    accent_soft {accent_soft}
    border      {border}
}}
",
        bg = hex_to_kara(&c.bg0.to_hex()),
        surface = hex_to_kara(&c.bg1.to_hex()),
        text = hex_to_kara(&c.fg0.to_hex()),
        text_muted = hex_to_kara(&c.fg_muted.to_hex()),
        accent = hex_to_kara(&c.accent.to_hex()),
        accent_soft = hex_to_kara(&c.accent_soft.to_hex()),
        border = hex_to_kara(&c.border_subtle.to_hex()),
    )
}
