use crate::ResolvedTheme;

pub fn render_session_theme(theme: &ResolvedTheme) -> String {
    format!(
        "# generated by kara-beautify
export GTK_THEME={}
export XCURSOR_THEME={}
export XCURSOR_SIZE={}
",
        theme.gtk_theme_name(),
        theme.cursor.theme,
        theme.cursor.size,
    )
}
