use crate::ResolvedTheme;

pub fn render_tmux_theme(theme: &ResolvedTheme) -> String {
    let c = &theme.semantic;
    format!(
        "# generated by kara-beautify

set -g status-style \"bg={},fg={}\"

set -g pane-border-style \"fg={}\"
set -g pane-active-border-style \"fg={}\"

set -g message-style \"bg={},fg={}\"

set -g status-left-style \"bg={},fg={}\"
set -g status-right-style \"bg={},fg={}\"

set -g window-status-style \"bg={},fg={}\"
set -g window-status-current-style \"bg={},fg={}\"

set -g mode-style \"bg={},fg={}\"

set -g status-justify left
set -g status-left-length 30
set -g status-right-length 100
",
        c.bg1.to_hex(),
        c.fg0.to_hex(),
        c.border_subtle.to_hex(),
        c.border_strong.to_hex(),
        c.accent.to_hex(),
        c.accent_contrast.to_hex(),
        c.bg1.to_hex(),
        c.accent.to_hex(),
        c.bg1.to_hex(),
        c.fg_muted.to_hex(),
        c.bg1.to_hex(),
        c.fg_muted.to_hex(),
        c.bg1.to_hex(),
        c.accent.to_hex(),
        c.accent.to_hex(),
        c.accent_contrast.to_hex(),
    )
}
