use std::path::Path;
use std::process::{Command, Stdio};

#[derive(Debug, Clone, Default)]
pub struct ReloadPlan {
    pub kara_gate: bool,
    pub kitty: bool,
    pub foot: bool,
    /// When `foot` is true, this holds the OSC escape-sequence payload
    /// to broadcast to every pts. Generated by
    /// `kara_theme::render::foot::render_foot_osc_sequences`.
    pub foot_osc: String,
    /// Whether the theme's active mode is dark. Kept for backward
    /// compatibility with existing callers; OSC reload does not use
    /// it since the sequence encodes colors directly.
    pub foot_dark: bool,
    pub tmux: bool,
    pub nvim: bool,
}

impl ReloadPlan {
    pub fn any(&self) -> bool {
        self.kara_gate || self.kitty || self.foot || self.tmux || self.nvim
    }
}

fn run_shell(command: &str) {
    let _ = Command::new("sh")
        .arg("-lc")
        .arg(command)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();
}

pub fn reload_kara_gate() {
    // Try IPC first, fall back to signal
    if let Ok(mut client) = kara_ipc::client::IpcClient::connect() {
        let req = kara_ipc::Request::ThemeChanged {
            theme_name: String::new(),
        };
        let _ = client.request(&req);
    } else {
        run_shell(r#"pidof kara-gate >/dev/null 2>&1 && kill -HUP "$(pidof kara-gate)" || true"#);
    }
}

pub fn reload_kitty() {
    run_shell(r#"pidof kitty >/dev/null 2>&1 && pkill -USR1 -x kitty || true"#);
}

/// Broadcast an OSC-escape-sequence color payload to every pts
/// device the current user can write to. Bypasses foot's config
/// reload entirely: the escape sequences are parsed by foot's
/// live terminal emulator loop, which reprograms its palette /
/// fg / bg / cursor / selection colors in place. No restart, no
/// file patching, no cached-section SIGUSR dance.
///
/// Writes also land in kitty, alacritty, xterm, and any other
/// xterm-compatible terminal that honors OSC 4/10/11/12/17/19 —
/// this is intentional, since OSC is the standards-track way to
/// retheme a running terminal. Opening each pts is best-effort;
/// permission errors (other users' terminals) are silently
/// skipped.
///
/// Caveat: if a pts is currently attached to a TUI that's in
/// some alternate-screen mode, the OSC sequence may display as
/// garbage until the next redraw. In practice this is imperceptible
/// because the terminal applies the color change before handing
/// control back to the TUI, and the TUI re-renders its surface on
/// its next idle tick.
pub fn reload_foot(osc_payload: &str) {
    use std::fs::OpenOptions;
    use std::io::Write;

    if osc_payload.is_empty() {
        return;
    }

    let entries = match std::fs::read_dir("/dev/pts") {
        Ok(e) => e,
        Err(_) => return,
    };

    let mut written = 0usize;
    for entry in entries.flatten() {
        let path = entry.path();
        // Only numeric pts entries (skip `ptmx`, which is the master
        // device, and any other non-numeric special files).
        let numeric = path
            .file_name()
            .and_then(|n| n.to_str())
            .map(|s| s.chars().all(|c| c.is_ascii_digit()))
            .unwrap_or(false);
        if !numeric {
            continue;
        }
        // Writing to a pts that's currently controlled by a process
        // we don't own will fail with EACCES — fine, we skip it.
        if let Ok(mut f) = OpenOptions::new().write(true).open(&path) {
            if f.write_all(osc_payload.as_bytes()).is_ok() {
                written += 1;
            }
        }
    }

    tracing_log(&format!("reload_foot: OSC broadcast reached {written} pts"));
}

fn tracing_log(msg: &str) {
    // kara-beautify doesn't pull tracing today; keep a stderr path
    // so debug info surfaces in the daemon log without adding deps.
    eprintln!("kara-beautify: {msg}");
}

pub fn reload_tmux(theme_path: &Path) {
    let command = format!(
        "tmux source-file {} >/dev/null 2>&1 || true",
        theme_path.display()
    );
    run_shell(&command);
}

pub fn reload_nvim_sessions() {
    run_shell(
        r#"for sock in /tmp/nvim-kara-*.sock; do [ -S "$sock" ] || continue; nvim --server "$sock" --remote-send "<Esc>:silent! KaraReloadTheme<CR>" >/dev/null 2>&1 || true; done"#,
    );
}

pub fn apply_runtime_reloads(plan: ReloadPlan, tmux_theme_path: &Path) {
    if !plan.any() {
        return;
    }

    if plan.kara_gate {
        reload_kara_gate();
    }
    if plan.kitty {
        reload_kitty();
    }
    if plan.foot {
        reload_foot(&plan.foot_osc);
    }
    if plan.tmux {
        reload_tmux(tmux_theme_path);
    }
    if plan.nvim {
        reload_nvim_sessions();
    }
}
