[meta]
name = "natural"
mode = "dark"

[wallpaper]

[palette]
primary = "#d79921"
accent_strategy = "balanced"
contrast = "high"

[style]
radius = "none"
density = "compact"
surface_style = "flat"
transparency = 0.98
blur = false

[fonts]
ui_family = "FiraCode Nerd Font"
ui_size = 11
mono_family = "FiraCode Nerd Font"
mono_size = 13

[cursor]
theme = "Bibata-Modern-Amber"
size = 24

[nvim]
preset = "gruvbox"
transparent = true

[vwm_bar]
style = "docked"
background = true
modules = "flat"
icons = true
colors = true
minimal = false
height = 24
radius = 0
margin_x = 0
margin_y = 0
padding_y = 0
